import { homepage } from './home.mjs';
import { guidePages } from './guides.mjs';
export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const code = (text, language = 'Terminal') => `<div class="code-block"><div class="code-label"><span>${escape(language)}</span><button class="copy" type="button" aria-label="Copy code">Copy</button></div><pre><code>${escape(text)}</code></pre><span class="copy-status" role="status"></span></div>`;
export const capabilities = [
  ['01','Understand the system','Trace files, symbols, callers, dependencies, and entry points. Find the source behind the explanation.','fehm query "authentication flow"','TypeScript and JavaScript have the deepest analysis. Other supported languages have shallower resolution.'],
  ['02','Give agents focused context','Retrieve source excerpts, related tests, architecture rules and project history within a context budget.','fehm context "add refunds" --budget 4000','Token budgets are estimates for rendered context, not exact model token counts.'],
  ['03','Check architecture and practice drift','Compare changes with approved boundaries. Detect when engineering-practice evidence disappears.','fehm practices audit','31 static checks support review; they do not certify compliance or prescribe one universal architecture.'],
  ['04','Review and verify changes','Follow a diff through dependencies, inspect its blast radius, and run supported checks.','fehm impact --base HEAD~1','Verification runs project code and requires a trusted repository and its toolchain.'],
  ['05','Find quality and reliability gaps','Connect coverage, dependency risk, API contracts, infrastructure, and runtime evidence.','fehm health','Heuristic risk reports and static test reachability are not measured runtime guarantees.'],
  ['06','Engineer AI systems','Version prompts, review tool contracts, compare model behavior, and evaluate changes against held-out cases.','fehm ai-evaluations','Live evaluations require an explicitly configured provider. Costs and data transmission are opt-in.'],
  ['07','Keep the team in context','Watch repositories, explore the local cockpit, preserve decisions, and export onboarding notes.','fehm serve .fehm/graph.json --watch','Local operation supports trusted teams. It is not an isolated multi-tenant service.'],
  ['08','Testing & coverage','Inspect test quality, ingest measured coverage, and explore mutation testing and historical bug replay.','fehm test-quality','Without a coverage artifact, test reachability is a static estimate. Test execution requires a trusted repository.'],
  ['09','Security & delivery','Review security paths, dependency risk, API contracts, and infrastructure configuration together.','fehm security-graph','Supported static patterns provide review signals, not a complete vulnerability assessment.'],
  ['10','Review agent claims and outcomes','Check graph-backed claims and preserve agent outcomes, recurring mistakes, and resolution history.','fehm agent','Unsupported claims remain unverified. Recorded outcomes do not guarantee future agent behavior.'],
];
export const assistants = [
 ['claude','Claude Code','C','.claude','Use /fehm in Claude Code to map the current repository.'],
 ['cursor','Cursor','↗','.cursor','Select the Fehm skill in Cursor Agent and ask it to map the repository.'],
 ['codex','Codex','⌘','.agents','Mention $fehm in Codex CLI or the IDE extension.'],
 ['gemini','Gemini CLI','✧','.gemini','Ask Gemini to use the Fehm skill to map the current repository.'],
 ['copilot','Copilot CLI','⌥','.copilot','Run /skills reload, then /skills info fehm to confirm discovery.'],
 ['vscode','VS Code','⋈','.copilot','Reload VS Code and select Fehm in Copilot agent chat.'],
];
const intro = (label,title,description) => `<header class="page-intro"><p class="eyebrow">${label}</p><h1>${title}</h1><p class="lead">${description}</p></header>`;
const assistantCards = () => assistants.map(([id,name,mark])=>`<a class="integration-card" href="/integrations/${id}/"><span class="assistant-mark" aria-hidden="true">${mark}</span><span><strong>${name}</strong><small>Installation & setup</small></span><span class="link-arrow" aria-hidden="true">↗</span></a>`).join('');
export function pages(version) {
 const home = homepage(version, capabilities, assistants);
 const docsCards=[['open-source','Open-source foundations','Understand the components behind context and review.'],['open-code-review','Open Code Review','Add optional model-based code review.'],['overview','Introduction','Understand the graph and the local workflow.'],['installation','Installation','Set up the CLI with uv.'],['quickstart','Quickstart','Map a repository and ask a question.'],['cli','CLI reference','Explore, review, and operate from the terminal.'],['mcp','MCP connection','Expose graph tools to your assistant.'],['architecture','Architecture & drift','Choose policies and compare evidence.'],['verification','Change verification','Inspect impact and run checks.'],['cockpit','Local cockpit','Run a private browser workspace.'],['ai','AI workflows','Review prompts and evaluate behavior.'],['troubleshooting','Troubleshooting','Resolve installation and runtime issues.'],['security','Security & privacy','Know the execution and data boundaries.']];
 const result=[
 {path:'/',title:'Codebase context for AI coding assistants',description:'Fehm is a local codebase graph for developers and coding assistants. Trace dependencies, review changes, and check architecture drift.',body:home},
 {path:'/features/',title:'Codebase intelligence features',description:'Explore Fehm’s ten capability groups, from source graphs and context retrieval to engineering-practice drift and change verification.',body:intro('Product','Code graphs, context<br><em>and change review.</em>','Ten ways to work with the same local graph. Explore the commands and the limits of each workflow.')+capabilities.map(([n,title,description,command,limit])=>`<section class="feature-detail" id="capability-${n}" data-reveal><span class="chapter">${n}</span><div><h2>${title}</h2><p>${description}</p>${code(command)}<p class="limitation">${limit}</p></div></section>`).join('')},
 {path:'/getting-started/',title:'Get started with Fehm',description:'Install a Fehm wheel using uv, register your assistant, scan a repository, and open the localhost cockpit.',body:intro('Get started','Install Fehm and scan a repository.','Install the local tool, choose an assistant, and start with a repository you know.')+`<div class="note"><strong>Install with uv</strong><p>Use a Fehm wheel supplied by the project maintainer. A public package download is not available from this website yet.</p></div><div class="setup-flow"><section><span class="chapter">01</span><h2>Install Fehm</h2><p>With uv installed, point it at your supplied wheel. Replace PLATFORM with its actual platform tag:</p>${code(`uv tool install /path/to/fehm-${version}-py3-none-PLATFORM.whl\nuv tool update-shell\nfehm --version`)}<p>Follow the <a href="/docs/installation/">installation guide</a> for setup and upgrades. No separate npm or Node installation is required to run the packaged tool.</p></section><section><span class="chapter">02</span><h2>Connect your assistant</h2>${code('fehm install --platform claude')}<p>Choose your platform in the <a href="/integrations/">integration guides</a>. Add <code>--project</code> from a repository root for a project-scoped skill.</p></section><section><span class="chapter">03</span><h2>Scan and explore</h2>${code('cd /absolute/path/to/project\nfehm scan .\nfehm query "authentication flow"\nfehm serve .fehm/graph.json --watch')}<p>The cockpit opens at <code>http://127.0.0.1:7331</code>. Ask your assistant to explain the flow and cite the returned files.</p></section></div>`},
 {path:'/integrations/',title:'Coding assistant integrations',description:'Connect Fehm to Claude Code, Cursor, Codex, Gemini CLI, Copilot CLI, or VS Code with personal or repository-scoped skills.',body:intro('Integrations','Connect Fehm to<br><em>your coding assistant.</em>','Register Fehm once, then let your assistant work from a persistent repository graph.')+`<div class="integration-grid">${assistantCards()}</div><a class="integration-card" href="/docs/open-code-review/"><span><strong>Open Code Review</strong><small>Optional AI review with your chosen provider</small></span><span class="link-arrow">↗</span></a><section class="section"><h2>Built into your Fehm workflow.</h2><p>Selected components from Graft, Everything Claude Code and Codebase Memory support context selection and retrieval. Agency Agents and gstack contribute review guidance and source-freshness checks.</p><a class="quiet-link" href="/docs/open-source/">Explore the open-source foundations →</a></section><section class="two-column section"><div><h2>Choose your scope.</h2><p>Personal skills work across projects. A project skill belongs to one repository and can be shared with its contributors.</p>${code('fehm install --platform codex --project')}</div><div><h2>Prefer MCP?</h2><p>Clients supporting stdio MCP can query the graph directly. Skill registration and MCP configuration are independent options.</p><a class="quiet-link" href="/docs/mcp/">Configure an MCP connection →</a><h3 class="spaced">Other assistants</h3><p><code>fehm install --platform generic --project</code> writes a standard skill under <code>.agents/skills</code>. Discovery depends on your client.</p></div></section>`},
 {path:'/docs/',title:'Fehm documentation',description:'On-site guides for installation, source graphs, CLI commands, MCP, architecture drift, verification, and troubleshooting.',body:intro('Documentation','Start here.','Practical guides for working with Fehm, from a first scan to a reviewed change.')+`<label class="docs-search"><span>Find a guide</span><input id="docs-search" type="search" placeholder="Search documentation…" autocomplete="off" aria-controls="guide-list"></label><p id="search-status" class="search-status" role="status"></p><div class="docs-grid" id="guide-list">${docsCards.map(([slug,title,desc])=>`<a class="doc-card" data-event="docs_click" href="/docs/${slug}/" data-search="${escape(title+' '+desc)}"><h2>${title}</h2><p>${desc}</p><span aria-hidden="true">↗</span></a>`).join('')}</div>`},
 {path:'/engineering-practices/',title:'Architecture and engineering-practice drift',description:'Keep changes aligned with your project’s approved architecture and detect lost engineering-practice evidence.',body:intro('Engineering practices','A boundary worth<br><em>making visible.</em>','Review how the code changes against the decisions your team has made.')+`<div class="boundary-figure"><span>Controller</span><i aria-hidden="true">→</i><span>Service</span><i aria-hidden="true">→</i><span>Database</span><p>Example: approved dependency direction</p></div><div class="two-column section"><section><h2>Architecture drift</h2><p>A new import can cross an approved layer boundary. Fehm identifies the relationship and the rule it conflicts with. Resolving another violation does not conceal a new one.</p></section><section><h2>Practice drift</h2><p>A test, CI configuration, or other control can disappear from the evidence recorded in a baseline. Fehm reports the lost signal so it can be reviewed.</p></section></div><div class="prose"><h2>Approve the rules you need.</h2>${code('fehm practices audit\nfehm practices propose --profile auto\n# Review .fehm/practices.proposed.json\nfehm practices approve\nfehm practices baseline')}<p>31 static signals cover common software and AI engineering concerns. They support review without claiming standards compliance. Choose required rules, warnings, and reasoned exemptions for your project.</p><a class="quiet-link" href="/docs/architecture/">Read the policy and drift guide →</a></div>`},
 {path:'/releases/',title:'Fehm release history',description:'What you can do with the current version of Fehm.',body:intro('Release history',`Version ${escape(version)}`,'Explore the capabilities included in this version.')+`<div class="prose"><h2>Local installation</h2><p>The uv wheel packages the compiled engine with a private Node runtime dependency. Assistant registration supports personal and repository scopes.</p><h2>Source context and review</h2><p>Scan repositories, retrieve graph-backed context, inspect change impact, and compare approved architecture and engineering-practice evidence.</p><h2>Context and review improvements</h2><p>Context packets keep their strongest anchors and then rotate across relevant files. Identifier handling recognizes acronym boundaries, while memory selection prioritizes task and technology matches. Optional model review includes a guidance profile and indexed-source freshness checks.</p><p><a href="/docs/open-source/">See which components support these workflows</a>.</p><h2>Local operation</h2><p>The browser cockpit, watch mode, and stdio MCP expose the same engine through different interfaces.</p><h2>Availability</h2><p>Follow the <a href="/docs/installation/">installation guide</a> to install a supplied wheel with uv and connect your assistant.</p></div>`},
 {path:'/privacy/',title:'Privacy and analytics',description:'How Fehm handles local source processing and optional website measurement.',body:intro('Privacy','Privacy and analytics.','Local code intelligence and public website measurement are separate.')+`<div class="prose"><h2>Your repository</h2><p>This website does not connect to your local graph or receive source code, prompts, repository paths, or localhost activity. Fehm scans and queries locally. Explicitly invoked provider features may send configured model inputs to the endpoint you choose.</p><h2>Website analytics</h2><p>When configured, Google Analytics loads only after you accept optional measurement. The site records sanitized page views and selected guide-navigation events. Page locations exclude query strings and URL fragments; the implementation does not send user IDs or repository content.</p><p>Measurement does not identify every visitor. Browser settings, blockers, and consent choices affect the data. The hosting provider may retain access logs under its own policies.</p><h2>Your choice</h2><p>When optional measurement is configured, you can change your preference here. The browser stores that preference locally. Rejecting prevents the tag from loading; withdrawing consent stops future measurement on the page. It does not delete data previously received by Google.</p><button type="button" class="header-cta" id="privacy-preferences" hidden>Change cookie preference</button><h2>Using Fehm privately</h2><p><a href="/docs/security/">Read the security guide</a> to understand local processing, command execution, and optional model-provider use.</p></div>`},
 ];
 for(const [id,name,mark,folder,invocation] of assistants) {
  const projectFolder=['copilot','vscode'].includes(id)?'.github':folder;
  result.push({path:`/integrations/${id}/`,kind:'integration',assistant:id,title:`Fehm with ${name}`,description:`Set up Fehm in ${name}. Install the skill, choose a scope, build a local graph, and query repository context.`,body:`<p>Give ${name} a repeatable way to map a repository and retrieve source-backed context. Install the Fehm CLI first using the <a href="/docs/installation/">installation guide</a>.</p><h2>Install and register</h2>${code(`fehm install --platform ${id}`)}<p>This registers a personal skill at <code>~/${folder}/skills/fehm/SKILL.md</code>. For a project-only setup, run from the repository root:</p>${code(`fehm install --project --platform ${id}`)}<p>Project scope writes <code>${projectFolder}/skills/fehm/SKILL.md</code>. The installer reports the path and preserves customized files.</p><h2>Build the graph</h2><p>${invocation} Restart or reload the assistant if it has not discovered the skill.</p>${code('fehm scan .')}<p>The graph is stored in <code>.fehm/graph.json</code>. Run scans from the repository being analyzed, not the skill installation folder.</p><h2>Ask with context</h2><blockquote>Use Fehm to explain the authentication flow. Cite source files and distinguish explicit relationships from inferred ones.</blockquote><p>You can also retrieve the context in a terminal:</p>${code('fehm query "authentication flow"')}<h2>Keep the integration current</h2><p>Install the next supplied wheel, then refresh the original scope:</p>${code(`fehm install --platform ${id}\nfehm integrations --platform ${id}`)}<p>Add <code>--project</code> if that was your installation scope. Once the registry package is released, use <code>uv tool upgrade fehm</code> before re-registering.</p><h2>Troubleshooting</h2><p>Confirm the CLI is on the assistant terminal’s PATH and the skill is in the intended scope. Remote hosts need their own Fehm installation. If the skill does not appear, reload your assistant and check that skills are enabled.</p><p><a href="/docs/troubleshooting/">More troubleshooting</a> · <a href="/docs/mcp/">Connect with MCP instead</a></p>`});
 }
 return [...result,...guidePages(version)];
}
