import { code } from './content.mjs';
export const guideNavigation = [
  ['overview','Introduction'],['installation','Installation'],['quickstart','Quickstart'],
  ['open-code-review','Open Code Review'],['open-source','Open-source foundations'],['cli','CLI reference'],['mcp','MCP connection'],['architecture','Architecture & drift'],
  ['verification','Change verification'],['cockpit','Local cockpit'],['ai','AI workflows'],
  ['troubleshooting','Troubleshooting'],['security','Security & privacy'],
];
export function guidePages(version) {
  const articles = {
    'open-source': ['Open-source foundations','How selected open-source components improve the Fehm workflows you already use.',`
      <p>Fehm combines its own repository graph with selected open-source components. Context improvements run through your existing commands. Model-based review is an optional workflow you configure separately.</p>
      <h2>Context that spans relevant files</h2><p>Graft contributes a file-selection algorithm. Fehm keeps the three strongest ranked results first, then rotates the remaining candidates across files. This helps reduce repeated-file crowding within a context budget. Small budgets can still omit files; search scores remain unchanged.</p>${code('fehm scan .\nfehm context "change authentication" --budget 4000')}
      <h2>Find code and relevant decisions</h2><p>Codebase Memory contributes identifier-boundary logic, helping retrieval recognize names such as HTTPServer and XMLParser. Everything Claude Code contributes relevance-ranking logic that prioritizes stored decisions and warnings matching your question or detected technologies. Neither requires a separate installation.</p>
      <h2>Review changes with source context</h2><p>Open Code Review is bundled in Fehm’s platform-specific wheel. Configure your model provider, preview a review, then explicitly allow provider execution. Fehm can supply a context packet and link returned findings to indexed source locations.</p><p>Agency Agents contributes the optional code-review guidance profile, covering correctness, security, maintainability, performance and tests. gstack contributes the source-freshness classification used to report whether indexed source changed during review or was already stale.</p>${code('fehm review --context "authentication changes" --profile code-review --graph-report')}<p>This command previews the plan. Follow the <a href="/docs/open-code-review/">Open Code Review guide</a> to configure and run it. Findings remain model-generated claims. Freshness checks cover indexed files, not new files outside the index, and cannot detect files changed and restored between snapshots.</p>
      <h2>What you install</h2><p>Your Fehm wheel includes these selected adaptations and their license notices. You do not need to install the five source projects separately. They are not additional assistant integrations or complete installations of those products. Ordinary graph queries remain local; configured model review can send source to your provider.</p>
      <h2>Project credits</h2><p>Selected source adaptations use MIT licenses: Graft, Everything Claude Code, gstack, Agency Agents and Codebase Memory. The bundled Open Code Review engine uses Apache-2.0. Pinned source manifests and license notices ship with Fehm.</p>`],
    'open-code-review': ['Open Code Review','Review changes with the engine included in Fehm’s platform-specific package.',`
      <p>Fehm includes Open Code Review for optional model-based review. It can use Fehm’s repository context and return findings linked to indexed source locations.</p>
      <h2>Configure your provider</h2><p>No separate Open Code Review or npm installation is needed with the bundled wheel. Git 2.41 or newer is required for Git workflows. Configuration may test provider connectivity.</p>${code('fehm review engine-version\nfehm review configure provider\nfehm review configure model')}
      <h2>Preview the workflow</h2>${code('fehm scan .\nfehm review --context "authentication changes" --graph-report')}<p>Without <code>--allow-provider</code>, Fehm only shows the plan.</p>
      <h2>Review with repository context</h2>${code('fehm review --context "authentication changes" --graph-report --allow-provider')}<p>Diff reviews can receive a budgeted Fehm context packet. Full-file scans do not support the context handoff. It may read additional source and invoke configured tools. Review its settings first; provider charges may apply. Its own session history may retain review inputs.</p>
      <h2>Choose review guidance</h2><p>Add <code>--profile code-review</code> for an evidence-focused checklist covering correctness, security, performance and tests. The profile applies to diff reviews and is optional.</p><h2>Read source-linked findings</h2><p>The report retains upstream warnings and review status, and links findings to overlapping graph locations. Model claims remain unverified. The report also compares indexed source before and after the review and flags stale or changed files. This excludes new files outside the index. Rescan changed source before reviewing. Fehm does not apply suggestions or post comments automatically.</p>
      <h2>Choose a scope</h2>${code('fehm review --from main --to my-feature --allow-provider\nfehm review --scan --path src --allow-provider')}<p>Use <code>--repo /path/to/project</code> for another repository. The default timeout is five minutes. Omit <code>--graph-report</code> for the original upstream JSON format.</p>`],
    overview: ['Introduction to Fehm','A local graph of your repository, available to you and your coding assistant.',`
      <p>Fehm extracts files, symbols, imports, calls, and other relationships into a persistent graph. You can query that graph from the terminal, connect it to an assistant through a skill or MCP, or explore it in a local browser.</p>
      <h2>What the graph contains</h2><p>Relationships carry provenance, confidence, and source locations where available. TypeScript and JavaScript use compiler-backed analysis. Python, Go, Rust, and Java use shallower deterministic extraction.</p>
      <h2>Choose a starting point</h2><div class="next-links"><a href="/docs/installation/">Install Fehm <span>Set up the CLI with uv.</span></a><a href="/docs/quickstart/">Map a repository <span>Scan, query, and inspect your first graph.</span></a><a href="/integrations/">Connect an assistant <span>Choose your editor or terminal agent.</span></a></div>
      <h2>What runs locally</h2><p>Scanning and ordinary graph queries do not call a model provider. Evaluation and semantic-summary features make provider calls only when configured and invoked. Verification can execute the analyzed project’s own commands.</p>
      <h2>Current scope</h2><p>TypeScript project aliases and references may leave relationships unresolved. Python, Go, Rust, and Java have less detailed resolution than TypeScript and JavaScript. Check the cited source when interpreting a result.</p>`],
    installation: ['Installation','Install the packaged CLI with uv. No separate Node or npm installation is needed to use it.',`
      <div class="note"><strong>Install with uv</strong><p>Use a Fehm wheel supplied by the project maintainer. A public package download is not available from this website yet.</p></div>
      <h2>Install a supplied wheel</h2><p>Install uv first, then run the following with the path to the wheel you received (replace PLATFORM with the actual filename’s platform tag):</p>${code(`uv tool install /path/to/fehm-${version}-py3-none-PLATFORM.whl\nuv tool update-shell\nfehm --version`)}<p>Open a new terminal if the command is not found. uv creates an isolated environment and installs Fehm’s private Node runtime dependency. The first installation requires network access for dependencies.</p>
      <h2>Upgrade or remove</h2>${code('uv tool install --force /path/to/new-fehm.whl\n# Refresh your chosen assistant skill afterward\nfehm install --platform claude\n\n# Remove the skill before uninstalling the CLI\nfehm uninstall --platform claude\nuv tool uninstall fehm')}<p>Once the registry release exists, use <code>uv tool upgrade fehm</code>. Stop watchers before an upgrade and retain your project’s policies and history.</p>
      <h2>Project tools are separate</h2><p>Fehm’s runtime does not install your project’s dependencies. Git features need Git; test and build execution needs your project’s own toolchain.</p>`],
    quickstart: ['Map your first repository','Build the graph, retrieve a known flow, and open the local cockpit.',`
      <h2>1. Work from your project</h2>${code('cd /absolute/path/to/project\nfehm scan .\nfehm stats')}<p>The scan writes <code>.fehm/graph.json</code> and supporting state. Common build/dependency directories are excluded, including <code>node_modules</code>, <code>.venv</code>, and <code>dist</code>. General <code>.gitignore</code> matching is not implemented.</p>
      <h2>2. Ask a specific question</h2>${code('fehm query "authentication flow"\nfehm context "change authentication" --budget 4000')}<p>The result is a context packet containing source evidence, not a model-generated answer. Read the cited files or ask your assistant to explain the packet. Token budgets are character-based estimates.</p>
      <h2>3. Follow relationships</h2>${code('fehm relationships authenticate --direction both\nfehm what-breaks authenticate')}<p>Replace <code>authenticate</code> with a symbol that exists in your repository. Dynamic relationships may remain unresolved; inferred results should be checked against source.</p>
      <h2>4. Explore in the browser</h2>${code('fehm serve .fehm/graph.json --watch')}<p>Open <code>http://127.0.0.1:7331</code>. Watch mode refreshes the graph after source changes. Stop with Ctrl+C.</p>
      <h2>Next steps</h2><p><a href="/integrations/">Register an assistant</a> to reuse this workflow, or <a href="/docs/architecture/">review engineering practices</a> before making a change.</p>`],
    cli: ['CLI reference','Common commands for graph exploration, context, review, and operation.',`
      <h2>Graph and retrieval</h2>${code('fehm scan [repository] [--out directory]\nfehm stats [graph.json]\nfehm query "question" [graph.json] --budget 4000\nfehm focus "symbol" [graph.json] --depth 2\nfehm relationships "symbol" --direction both\nfehm search "query" --limit 10')}<p>Commands that accept an optional graph default to <code>.fehm/graph.json</code>. Use an absolute graph path when working outside the indexed repository. <code>query</code> is an alias for context retrieval.</p>
      <h2>Review and quality</h2>${code('fehm impact --base HEAD~1\nfehm preflight --base HEAD~1 --understand "describe the change"\nfehm verify --no-commands\nfehm practices audit\nfehm health\nfehm production-audit')}<p>Choose a Git base that exists. Remove <code>--no-commands</code> only when you want verification to run project commands.</p>
      <h2>Assistant registration</h2>${code('fehm install --platform codex --project\nfehm integrations --platform codex --project\nfehm uninstall --platform codex --project')}<p>Omit <code>--project</code> for personal scope. Use <code>--dry-run</code> before registration changes. Customized skills are protected; <code>--force</code> backs them up before replacement.</p>
      <h2>Operation and help</h2>${code('fehm serve .fehm/graph.json --watch --port 7331\nfehm mcp /absolute/path/to/.fehm/graph.json\nfehm --version\nfehm --help')}<p><code>--help</code> lists the full CLI surface. Many reports accept <code>--json</code> for programmatic consumption. Practice audits return exit code 2 for required gaps or baseline regressions and exit code 1 for invalid configuration.</p>`],
    mcp: ['Connect through MCP','Expose graph tools to a client using the installed Fehm executable.',`
      <h2>Prepare the graph</h2>${code('fehm scan .\nuv tool dir --bin')}<p>The second command reports the executable directory. Use the absolute path to its <code>fehm</code> executable, or <code>fehm.exe</code> on Windows. Skill registration and MCP configuration are separate.</p>
      <h2>Configure a stdio server</h2>${code('{\n  "mcpServers": {\n    "fehm": {\n      "command": "/absolute/path/to/bin/fehm",\n      "args": ["mcp", "/absolute/path/to/project/.fehm/graph.json"]\n    }\n  }\n}', 'JSON')}<p>Use your client’s actual configuration schema. VS Code uses a <code>servers</code> map. Codex uses TOML:</p>${code('[mcp_servers.fehm]\ncommand = "/absolute/path/to/bin/fehm"\nargs = ["mcp", "/absolute/path/to/project/.fehm/graph.json"]','TOML')}
      <h2>Verify the connection</h2><p>Reload the client and confirm it discovers <code>fehm_context</code> and <code>fehm_practices</code>. Ask it to retrieve a known flow and check the returned source paths.</p>
      <h2>Keep the graph current</h2><p>MCP does not require the HTTP cockpit. Refresh the graph with a scan or a separate watcher. Do not run multiple writers against the same repository state. Tools that execute code or call providers remain explicit operations.</p>`],
    architecture: ['Architecture and practice drift','Compare changes with the boundaries and controls your project has chosen.',`
      <h2>Architecture drift</h2><p>An approved architecture defines allowed dependencies. If your project requires controllers to use a service layer, a new direct database import can violate that contract. New violations are reported even if the same change resolves an older one.</p>${code('fehm architecture propose\n# Review .fehm/architecture.proposed.json\nfehm architecture approve')}
      <h2>Engineering-practice drift</h2><p>The practice catalog checks for 31 signals across development, testing, delivery, security, reliability, operations, accessibility, and AI. A saved baseline can reveal a previously detected signal that has disappeared.</p>${code('fehm practices audit\nfehm practices propose --profile auto\n# Review and edit .fehm/practices.proposed.json\nfehm practices approve\nfehm practices baseline')}
      <h2>Choose what to enforce</h2><table><thead><tr><th>Mode</th><th>Behavior</th></tr></thead><tbody><tr><td>warn</td><td>Report evidence gaps without making them mandatory.</td></tr><tr><td>require</td><td>Require a detected signal after policy approval.</td></tr><tr><td>off</td><td>Record an exemption with a non-empty reason.</td></tr></tbody></table><p>Profiles are <code>auto</code>, <code>library</code>, <code>service</code>, and <code>ai-service</code>. Review applicability before approval.</p>
      <h2>Interpret the result</h2><p>A matching artifact does not prove a control works. Fehm does not prescribe one universal architecture or intercept editor keystrokes. Keep formatting, language-specific linting, runtime checks, and human review in the workflow.</p>`],
    verification: ['Review a change','Use the graph to inspect affected code and run the checks your project provides.',`
      <h2>Inspect impact</h2>${code('fehm impact --base HEAD~1\nfehm preflight --base HEAD~1 --understand "change authentication"')}<p>Impact reports follow the diff through graph relationships to affected symbols, files, and tests. Static reachability is evidence for review, not proof of every runtime consequence.</p>
      <h2>Run verification</h2>${code('fehm verify --no-commands\n# Run project commands only in a trusted environment\nfehm verify')}<p>Verification combines graph/freshness checks, architecture rules, static security checks, and supported project scripts. Install the target project’s dependencies first.</p>
      <h2>Policy gates</h2><p>Preflight combines architecture, protected zones, understanding, risk, and approved required practices. An explicit approval override is recorded in the report. Invalid policy data fails closed rather than silently disabling enforcement.</p>
      <h2>Mutation and historical replay</h2><p>Fehm also exposes mutation testing and historical bug reproduction. These workflows execute project code in copies or checkouts; they are not security sandboxes. Use disposable trusted repositories and inspect <code>fehm --help</code> before running them.</p>`],
    cockpit: ['The local cockpit','Explore the graph, reports, and prompts in a browser on your own machine.',`
      <h2>Start a local session</h2>${code('fehm serve .fehm/graph.json --watch')}<p>Open <code>http://127.0.0.1:7331</code>. The CLI binds to loopback by default. Add <code>--port 7441</code> when the default port is in use.</p>
      <h2>Multiple projects</h2>${code('fehm serve /path/to/a/.fehm/graph.json /path/to/b/.fehm/graph.json --watch')}<p>Use the project switcher to select the repository. Each graph must reference a source directory available to the server. Rescan after moving a repository.</p>
      <h2>Remote access</h2><p>Non-loopback binding requires a bearer token of at least 32 characters unless explicitly bypassed. Prefer a trusted TLS proxy or SSH forwarding. Projects share authentication in one process; this is not multi-tenant hosting.</p>
      <h2>Stop and restart</h2><p>Stop the foreground process with Ctrl+C and restart with the same command. For Linux services, use a path without spaces.</p>`],
    ai: ['AI engineering workflows','Review prompts and tool contracts, then evaluate with an explicitly configured provider.',`
      <h2>Local analysis first</h2><p>Prompt analysis produces structural findings, ambiguity and conflict checks, security findings, and evaluation cases. Prompt histories preserve versions and reasons for changes. These local reports do not need a model key.</p>
      <h2>Live evaluations</h2><p>Provider-backed workflows can execute cases, retain outputs and errors, compare models, and inspect behavioral differences. You choose the endpoint, model, and environment variable containing credentials. Consult <code>fehm --help</code> for the prompt subcommands and configuration flags.</p>
      <h2>Promotion with held-out cases</h2><p>Prompt optimization uses bounded candidate strategies and a separate held-out promotion gate. Evaluator scores are model-produced evidence, not proof of correctness. Small test suites can miss regressions.</p>
      <h2>Graph-backed claims</h2>${code('fehm ai-evaluations\nfehm agent analytics')}<p>Agent records and evaluation graphs connect prompts, tests, tools, and outcomes. Claim verification checks concrete repository statements and leaves unsupported absolutes unverified.</p>
      <h2>Control the boundary</h2><p>Provider calls may transmit prompts and selected source context. Review data handling, budget, latency, credentials, and failure behavior before a live run. Start with a small evaluation to check the provider configuration.</p>`],
    troubleshooting: ['Troubleshooting','Resolve installation, graph, assistant, and localhost issues.',`
      <h2>The command is missing</h2>${code('uv tool list\nuv tool update-shell')}<p>Open a new terminal. GUI assistants may need a restart to inherit PATH. Check for another Fehm installation shadowing the uv executable.</p>
      <h2>The assistant cannot find the skill</h2>${code('fehm integrations --platform claude\nfehm integrations --platform claude --project')}<p>Use your actual platform. These commands check different scopes. Reload the assistant and confirm skills are enabled. Remote terminals require their own installation.</p>
      <h2>The graph is missing or stale</h2>${code('fehm scan .')}<p>Run from the repository root. Graphs contain an absolute source root, so moving the repository requires a rescan. Check that watch mode points at the intended graph and only one writer is active.</p>
      <h2>The server does not open</h2><p>Try a different port and confirm the supplied graph exists. A listener permission error can mean your execution environment disallows loopback servers. An API 401 requires the configured token.</p>
      <h2>Practice audit exits with code 2</h2><p>Review the reported required gap or lost baseline signal. Do not reset the baseline simply to remove a failing result. Corrupt or edited active policies need a reviewed proposal and fresh approval.</p>
      <h2>Results miss a relationship</h2><p>Dynamic behavior, unsupported frameworks, TypeScript aliases/references, and shallow polyglot resolution can leave links unresolved. Compare evidence with the actual source and keep these limitations in the review.</p>`],
    security: ['Security and privacy','Understand the local processing, execution, and provider boundaries.',`
      <h2>Source processing</h2><p>Normal graph and practice analysis run locally. This public website has no connection to your local graph and does not receive your repository content.</p>
      <h2>Command execution</h2><p>Verification, mutation testing, and historical replay can execute repository code. Copies and checkouts protect a working tree but do not sandbox a malicious program. Use trusted repositories and appropriate isolation.</p>
      <h2>Private service operation</h2><p>The CLI defaults to loopback. Bearer authentication, request limits, and readiness probes support controlled private operation. Authentication is shared across projects in a server; there is no per-tenant isolation.</p>
      <h2>Policies and secrets</h2><p>Approval hashes detect local policy edits but are not identity or role-based authorization. Keep credentials outside source files and preserve access controls on local state. Back up approved policies, baselines, and durable histories.</p>
      <h2>External model calls</h2><p>Only explicitly configured provider features transmit model inputs. Treat retrieved and generated content as untrusted, review provider retention, and constrain tool permissions.</p>
      <h2>Reporting an issue</h2><p>Share a minimal sanitized reproduction privately with the project maintainer through an established private contact. Do not publish credentials or proprietary graph data. </p>`],
  };
  return guideNavigation.map(([slug])=>({path:`/docs/${slug}/`,kind:'docs',title:articles[slug][0],description:articles[slug][1],body:articles[slug][2]}));
}
