// Product diagrams explain implemented workflows; they are not live reports.
const icons = ['M4 5h6v6H4z M14 13h6v6h-6z M10 8h7v5','M4 5h16v14H4z M8 9h8 M8 13h5','M5 4v16 M19 4v16 M5 8h9 M10 16h9','M5 6h14 M5 12h9 M5 18h14','M4 17l5-7 4 3 7-8','M5 5h14v14H5z M9 9h6v6H9z','M4 7h16v12H4z M8 7V4h8v3','M5 12l4 4 10-10','M12 3l8 4v6c0 4-8 8-8 8s-8-4-8-8V7z','M5 4h14v16H5z M8 9h8 M8 13h8 M8 17h4'];
const icon = n => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]}"/></svg>`;
export function homepage(version, capabilities, assistants) {
return `<section class="product-hero">
 <div class="hero-copy"><a class="release-link" href="/releases/"><span class="live-dot"></span> Fehm ${version} <span>Release notes ↗</span></a><p class="eyebrow">CODEBASE INTELLIGENCE, ON YOUR MACHINE</p><h1>Know the code.<br><em>Understand</em><br>the change.</h1><p class="lead">Give your coding assistant the context behind the code. Explore dependencies, review changes, and keep engineering decisions in view.</p><div class="actions"><a class="button" href="/getting-started/" data-event="install_guide_click">Start with Fehm <span>↗</span></a><a class="quiet-link" href="/docs/">Explore the docs →</a></div><div class="hero-meta"><span>Local processing</span><span>Open source</span><span>No account</span></div></div>
 <div class="context-stage" data-reveal><div class="stage-top"><span class="stage-dots" aria-hidden="true">● ● ●</span><span>THE CONTEXT WORKFLOW</span><span>↗</span></div><div class="query-chip"><span>›</span> add refunds <small>your task</small></div><div class="context-stack"><div class="source-layer"><span class="file-symbol">{ }</span><div><strong>Relevant source</strong><small>Symbols, excerpts & locations</small></div><span class="layer-check">↗</span></div><div class="source-layer"><span class="file-symbol">⌁</span><div><strong>Connected evidence</strong><small>Relationships, tests & architecture</small></div><span class="layer-check">↗</span></div><div class="source-layer"><span class="file-symbol">≡</span><div><strong>Decision memory</strong><small>History & project context</small></div><span class="layer-check">↗</span></div></div><div class="packet"><div><span class="packet-label">FEHM CONTEXT</span><strong>One focused packet.</strong><small>Ranked evidence for your assistant</small></div><span class="packet-emblem" aria-hidden="true">↗</span></div><div class="stage-command"><span>$</span> fehm context "add refunds"</div><p class="diagram-label">Workflow illustration · results depend on repository evidence</p></div>
 </section>
 <section class="assistant-strip"><p>Bring the context to your coding assistant.</p><div>${assistants.map(([id,name])=>`<a href="/integrations/${id}/">${name}<span aria-hidden="true">↗</span></a>`).join('')}</div><a class="integration-more" href="/docs/mcp/">Connect other compatible clients with MCP →</a></section>
 <section class="section showcase-section"><div class="section-heading" data-reveal><div><p class="eyebrow">CONTEXT THAT CARRIES THROUGH</p><h2>From understanding<br>to <em>making the change.</em></h2></div><p>A shared source graph connects what you read, what you change, and what you check next.</p></div>
 <div class="showcase-grid"><article class="workflow-card drift-card" data-reveal><div class="card-copy"><span class="feature-kicker">01 / ENGINEERING PRACTICES</span><h3>Keep your decisions<br>from drifting.</h3><p>Approve the rules that fit your project. Compare current evidence with a saved baseline and review what disappeared.</p></div><div class="policy-art" role="img" aria-label="Practice drift workflow: approve project rules, save baseline evidence, review missing evidence"><div class="policy-heading"><span>Project policy</span><span>baseline → current</span></div><div class="policy-line"><i>✓</i><span>Approve the rules</span><b>Required / Advisory</b></div><div class="policy-line"><i>✓</i><span>Save the evidence</span><b>Baseline</b></div><div class="policy-line policy-alert"><i>!</i><span>Review lost signals</span><b>Needs review</b></div><div class="policy-foot">Your standards. An explicit review trail.</div></div><a class="card-link" href="/docs/architecture/">Explore architecture & drift <span>↗</span></a></article>
 <article class="workflow-card impact-card" data-reveal><div class="card-copy"><span class="feature-kicker">02 / CHANGE INTELLIGENCE</span><h3>A diff is only<br>the starting point.</h3><p>Follow changed files into affected dependencies, routes, and tests. Use the evidence to decide what deserves a closer look.</p></div><div class="impact-art" role="img" aria-label="Change impact workflow: project a Git diff onto the graph, inspect affected code, identify relevant tests"><div class="diff-sheet"><span>GIT DIFF</span><div><b>−</b><i></i></div><div><b>+</b><i></i></div><div><b>+</b><i></i></div></div><div class="impact-steps"><div><span>01</span>Changed symbols</div><div><span>02</span>Affected dependencies</div><div><span>03</span>Tests to inspect</div></div></div><a class="card-link" href="/docs/verification/">Explore change verification <span>↗</span></a></article></div><p class="workflow-note">These diagrams explain the workflow. Findings support review; they do not guarantee correctness.</p></section>
 <section class="section capability-section" id="capabilities"><div class="section-heading" data-reveal><div><p class="eyebrow">THE COMPLETE TOOLKIT</p><h2>One graph.<br><em>Ten ways to use it.</em></h2></div><p>The full feature set, organized around the work you do. Each group includes its commands and practical limits.</p></div><div class="capability-grid">${capabilities.map(([n,title,description],i)=>`<a class="capability-card" href="/features/#capability-${n}" data-reveal><div class="capability-top">${icon(i)}<span>${n} ↗</span></div><h3>${title}</h3><p>${description}</p><span class="capability-explore">Explore capability →</span></a>`).join('')}</div></section>
 <section class="local-band" data-reveal><div><p class="eyebrow">A LOCAL TOOL. A FAMILIAR WORKFLOW.</p><h2>It starts in<br><em>your repository.</em></h2><p>Install the packaged tool with uv, register your assistant, and scan. The graph stays on your machine. Provider features make external calls only when you configure and invoke them.</p><a class="quiet-link" href="/docs/installation/">Follow the installation guide →</a></div><div class="local-terminal"><div class="terminal-title"><span>~/your-project</span><span>TERMINAL</span></div><p><span>$</span> fehm scan .</p><p><span>$</span> fehm query "authentication flow"</p><p><span>$</span> fehm serve .fehm/graph.json --watch</p><div class="terminal-foot"><span class="live-dot"></span> CLI · MCP · localhost cockpit</div><a href="/releases/">What’s included in Fehm ↗</a></div></section>
 <section class="faq section"><div><p class="eyebrow">BEFORE YOU START</p><h2>A few<br><em>practical details.</em></h2></div><div><details><summary>Do I need npm to use Fehm?</summary><p>No. Install a supplied wheel with uv. The package includes the engine and installs a private Node runtime.</p></details><details><summary>Does a query call an AI model?</summary><p>Ordinary graph queries run locally and return evidence. Your coding assistant can use that evidence to explain the code. Model evaluation features require an explicitly configured provider.</p></details><details><summary>Which languages can I analyze?</summary><p>TypeScript and JavaScript have the deepest analysis. Python, Go, Rust, and Java have shallower declaration, import, and call resolution.</p></details><details><summary>Where should I start?</summary><p>Follow the <a href="/getting-started/">setup guide</a>, scan a repository you know, and ask about a familiar flow. Then <a href="/integrations/">connect your coding assistant</a> to reuse that context.</p></details></div></section>`;
}
